export function getData() {
  const data = {
    mediaType: [
      { name: "Article" },
      { name: "Podcast" },
      { name: "Video" },
      { name: "Infographic" },
    ],
    articleType: [{ name: "Essay" }, { name: "Digest" }],
    topics: [
      {
        data: { id: 1, name: "Astronomy", color: "bg-[#A44A3F]" },
        checked: false,
      },
      {
        data: { id: 2, name: "Biology", color: "bg-[#D15B2B]" },
        checked: false,
      },
      {
        data: { id: 3, name: "Chemical Engineering", color: "bg-[#E3954F]" },
        checked: false,
      },
      {
        data: { id: 4, name: "Chemistry", color: "bg-[#C39075]" },
        checked: false,
      },
      {
        data: { id: 5, name: "Computer Science", color: "bg-[#FFC834]" },
        checked: false,
      },
      {
        data: { id: 6, name: "Electrical Engineering", color: "bg-[#ACB377]" },
        checked: false,
      },
      {
        data: { id: 7, name: "Environment Science", color: "bg-[#54623A]" },
        checked: false,
      },
      {
        data: { id: 8, name: "Geology", color: "bg-[#387270]" },
        checked: false,
      },
      {
        data: { id: 9, name: "Mathematics", color: "bg-[#50A2A7]" },
        checked: false,
      },
      {
        data: { id: 10, name: "Mechanical Engineering", color: "bg-[#0A2B5E]" },
        checked: false,
      },
      {
        data: { id: 11, name: "Medicine", color: "bg-[#7282AC]" },
        checked: false,
      },
      {
        data: { id: 12, name: "Physics", color: "bg-[#AB95B3]" },
        checked: false,
      },
      {
        data: { id: 13, name: "Psychology", color: "bg-[#624563]" },
        checked: false,
      },
      {
        data: { id: 14, name: "Sociology", color: "bg-[#CC6666]" },
        checked: false,
      },
      {
        data: { id: 15, name: "Technology", color: "bg-[#4E413F]" },
        checked: false,
      },
    ],
    subtopics: [
      {
        id: 1,
        name: "Oncology",
        number_of_articles: 10,
        color: "",
        checked: false,
      },
      {
        id: 2,
        name: "Cardiology",
        number_of_articles: 3,
        color: "",
        checked: false,
      },
      {
        id: 3,
        name: "Rheumatology",
        number_of_articles: 5,
        color: "",
        checked: false,
      },
      {
        id: 4,
        name: "Mineralogy",
        number_of_articles: 7,
        color: "",
        checked: false,
      },
      {
        id: 5,
        name: "Geochemistry",
        number_of_articles: 1,
        color: "",
        checked: false,
      },
      {
        id: 6,
        name: "Paleontology",
        number_of_articles: 2,
        color: "",
        checked: false,
      },
      {
        id: 7,
        name: "Tectonics",
        number_of_articles: 4,
        color: "",
        checked: false,
      },
      {
        id: 8,
        name: "Artificial Intelligence",
        number_of_articles: 9,
        color: "",
        checked: false,
      },
      {
        id: 9,
        name: "Internet of things",
        number_of_articles: 0,
        color: "",
        checked: false,
      },
      {
        id: 10,
        name: "Robotics",
        number_of_articles: 1,
        color: "",
        checked: false,
      },
    ],
    subjects: [
      {
        id: 1,
        name: "Anatomy",
        number_of_articles: 7,
        color: "",
        checked: false,
      },
      {
        id: 2,
        name: "Biochemistry",
        number_of_articles: 3,
        color: "",
        checked: false,
      },
      {
        id: 3,
        name: "Genetics",
        number_of_articles: 1,
        color: "",
        checked: false,
      },
      {
        id: 4,
        name: "Nutrition",
        number_of_articles: 1,
        color: "",
        checked: false,
      },
      {
        id: 5,
        name: "Mineralogy",
        number_of_articles: 3,
        color: "",
        checked: false,
      },
      {
        id: 6,
        name: "Geochronology",
        number_of_articles: 2,
        color: "",
        checked: false,
      },
      {
        id: 7,
        name: "Geophysics",
        number_of_articles: 4,
        color: "",
        checked: false,
      },
      {
        id: 8,
        name: "Risk Management",
        number_of_articles: 6,
        color: "",
        checked: false,
      },
      {
        id: 9,
        name: "Programming",
        number_of_articles: 5,
        color: "",
        checked: false,
      },
      {
        id: 10,
        name: "Data Management",
        number_of_articles: 5,
        color: "",
        checked: false,
      },
    ],
    contributorType: [
      { id: 1, name: "Author" },
      { id: 2, name: "Illustrator" },
      { id: 3, name: "Animator" },
      { id: 4, name: "Photographer" },
      { id: 5, name: "Videographer" },
    ],
    contributors: [
      { id: 1, name: "John Smith", checked: false },
      { id: 2, name: "Jane Doe", checked: false },
      { id: 3, name: "Peter Jones", checked: false },
      { id: 4, name: "Mary Brown", checked: false },
      { id: 5, name: "David Williams", checked: false },
      { id: 6, name: "Elizabeth Wilson", checked: false },
      { id: 7, name: "Michael Johnson", checked: false },
      { id: 8, name: "Sarah Anderson", checked: false },
      { id: 9, name: "William Thomas", checked: false },
      { id: 10, name: "Jennifer White", checked: false },
      { id: 11, name: "Charles Green", checked: false },
      { id: 12, name: "Emily Black", checked: false },
      { id: 13, name: "Thomas Brown", checked: false },
      { id: 14, name: "Susan Williams", checked: false },
      { id: 15, name: "James Smith", checked: false },
      { id: 16, name: "Caroline Jones", checked: false },
      { id: 17, name: "Robert Wilson", checked: false },
      { id: 18, name: "Kimberly Taylor", checked: false },
      { id: 19, name: "Danielle Green", checked: false },
      { id: 20, name: "Michael Brown", checked: false },
    ],
  };

  return data;
}
